### ISSUE TITLE
Width/Height setting does not work correctly for portrait images

### ISSUE THREAD

**Issue by MHerbst** [MHerbst/mherbst-insert-thumbs-plugin#5]

**Comment by connectr** [comment]
Hi Martin,

First off, I just want to say thanks for taking the time to create this plugin. It's something that I think Koken is sorely missing and it's always cool to see to members of the community rise up to the challenge and fill the missing gaps.

I'm using the plugin on a clients site, who is a very active blogger and photographer. Everything was going great initially, but at some point yesterday, the images I was adding were no longer showing up.

I finally got them working again by using the preset width, but I'm pretty certain simply adding a width, disabling the crop and "use presets", was working as expected. 

Do you have any ideas why the resize by width would stop working? I've tried to find a way to access the error logs, but so far haven't had much luck in debugging it (even with Koken set to dev env).

On another note, do you have any plans on adding support for direct upload? It really would be the cherry on top, as the current workflow is a bit cumbersome and I'd prefer not having the blog images in the library. 

Lastly, I just wanted to say that you're plugin has been really useful in helping me understand Kokens plugin structure. I'll be using it as a reference to create my own Koken plugins at some point :)

Cheers,
Chris

**Comment by MHerbst** [comment]
Hi Chris,

nice to hear, that you like my plugin,

Right now I have no idea what's going wrong with the plugin. Can you send me settings that were not working (e.g. a screenshot). I can then try to reproduce it.
Unfortunately the Koken developers sometimes change APIs and then some plugins are no longer working correctly.
Because of these changes and the missing API documentation I have currently no plans in extending the plugin. In order to add e.g. a function to upload images I would need more internal information.

Regards
Martin

**Comment by connectr** [comment]
Hi Martin,

It seems everything works fine up until you set the image width to anything greater than 480px wide. 

Adding a height and ticking the crop option works too, but not simply resizing using the width.

So to confirm:

Setting the width to 300px, no float, no crop, no height = works.
Setting the width to 481px(+), no float, no crop, no height = fails.
Setting the width to 481px(+), height to anything, no float, no crop = works.

Cheers,
Chris
![screenshot 2015-04-13 13 45 54](https://cloud.githubusercontent.com/assets/109826/7115362/50f89a5c-e1e8-11e4-8e93-ca63579e8283.png)
![screenshot 2015-04-13 13 47 04](https://cloud.githubusercontent.com/assets/109826/7115361/50f6df5a-e1e8-11e4-86ad-3a3c4c34010b.png)

**Comment by connectr** [comment]
Here's another test case -> https://www.dropbox.com/s/76x0zhy5tfdwk77/Screenshot%202015-04-13%2014.46.29.png?dl=0

**Comment by MHerbst** [comment]
Hi Chris,

please excuse the later answer, but I was quite busy the last week. But I was able to figure out what's going wrong: it's just a simple typo in my PHP code. If the width is greater than 480 I set a preset value of "medium-large", but it has to be "medium_large". I have already commited the correction here on github.

**Comment by connectr** [comment]
Hey Martin,

No probs at all! I'm in the same boat, so I completely understand ;0)

Good news about the fix! I'm sure my client will be very happy to hear that, as she has been struggling with inserting images.

I'll take the latest version for a spin and let you know how it goes :)

Cheers,
Chris

**Comment by connectr** [comment]
Hi again,

Tested the update and all seems to be good :) I did notice that the images don't work if you have crop enabled, without specifying a height, but that isn't the end of the world :)
